name: 4G4P
version: '1.0-SNAPSHOT'
main: com.ariesninja.Game4G4P
api-version: '1.21'
commands:
  startround:
    description: Starts giving players random items every n seconds.
  stopround:
    description: Stops giving players random items.
  setitemcooldown:
    description: Changes the cooldown between item drops.
  resetscores:
    description: Reset all scoreboard data.